INFO: 2022-09-21 13:40:08,828 - Loading bot...
INFO: 2022-09-21 13:40:09,094 - Запуск основного цикла...
INFO: 2022-09-21 13:42:01,221 - Loading bot...
INFO: 2022-09-21 13:42:01,478 - Запуск основного цикла...
INFO: 2022-09-21 14:07:41,410 - Loading bot...
INFO: 2022-09-21 14:07:41,697 - Запуск основного цикла...
INFO: 2022-09-21 14:26:16,192 - Loading bot...
INFO: 2022-09-21 14:26:16,488 - Запуск основного цикла...
ERROR: 2022-09-21 14:26:35,724 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 39, in start
    keyboard=self.keyboard.get_keyboard('main'))
  File "C:\Users\Nata\PycharmProjects\VKAPI\keyboards.py", line 5, in get_keyboard
    with open(f'keyboards/{board_name}.json', 'r', encoding='utf-8') as kb:
FileNotFoundError: [Errno 2] No such file or directory: 'keyboards/main.json'

INFO: 2022-09-21 14:26:35,724 - Reloading...
INFO: 2022-09-21 14:26:41,020 - Запуск основного цикла...
INFO: 2022-09-21 14:29:06,756 - Loading bot...
INFO: 2022-09-21 14:29:07,039 - Запуск основного цикла...
ERROR: 2022-09-21 14:29:18,534 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 38, in start
    keyboard=self.get_keyboard('main'))
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 52, in get_keyboard
    with open(f'keyboards/{board_name}.json', 'r', encoding='utf-8') as kb:
FileNotFoundError: [Errno 2] No such file or directory: 'keyboards/main.json'

INFO: 2022-09-21 14:29:18,534 - Reloading...
INFO: 2022-09-21 14:29:23,884 - Запуск основного цикла...
INFO: 2022-09-21 14:32:48,434 - Loading bot...
INFO: 2022-09-21 14:32:48,739 - Запуск основного цикла...
ERROR: 2022-09-21 14:32:58,121 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 37, in start
    keyboard=self.get_keyboard('main'))
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 51, in get_keyboard
    with open(f'keyboards/{board_name}.json', mode='r', encoding='utf-8') as kb:
FileNotFoundError: [Errno 2] No such file or directory: 'keyboards/main.json'

INFO: 2022-09-21 14:32:58,121 - Reloading...
INFO: 2022-09-21 14:33:03,415 - Запуск основного цикла...
INFO: 2022-09-21 14:33:26,169 - Loading bot...
INFO: 2022-09-21 14:33:26,465 - Запуск основного цикла...
INFO: 2022-09-21 14:37:10,108 - Loading bot...
INFO: 2022-09-21 14:37:10,403 - Запуск основного цикла...
INFO: 2022-09-21 15:47:28,951 - Loading bot...
INFO: 2022-09-21 15:47:29,254 - Запуск основного цикла...
INFO: 2022-09-21 15:48:52,047 - Loading bot...
INFO: 2022-09-21 15:48:52,315 - Запуск основного цикла...
INFO: 2022-09-21 15:49:37,620 - Loading bot...
INFO: 2022-09-21 15:49:37,908 - Запуск основного цикла...
INFO: 2022-09-21 15:50:03,786 - Loading bot...
INFO: 2022-09-21 15:50:04,061 - Запуск основного цикла...
INFO: 2022-09-21 16:00:12,526 - Loading bot...
INFO: 2022-09-21 16:00:12,819 - Запуск основного цикла...
INFO: 2022-09-21 16:01:18,606 - Loading bot...
INFO: 2022-09-21 16:01:18,904 - Запуск основного цикла...
INFO: 2022-09-21 16:02:19,765 - Loading bot...
INFO: 2022-09-21 16:02:20,068 - Запуск основного цикла...
INFO: 2022-09-21 16:05:10,284 - Loading bot...
INFO: 2022-09-21 16:05:10,557 - Запуск основного цикла...
ERROR: 2022-09-21 16:05:15,157 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 35, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 46, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON

INFO: 2022-09-21 16:05:15,157 - Reloading...
INFO: 2022-09-21 16:05:20,443 - Запуск основного цикла...
ERROR: 2022-09-21 16:05:40,468 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 35, in start
    print(buttons)
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 46, in send_msg
    def send_msg(self, peer_id, msg, keyboard=None):
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON

INFO: 2022-09-21 16:05:40,469 - Reloading...
INFO: 2022-09-21 16:05:45,740 - Запуск основного цикла...
INFO: 2022-09-21 16:05:48,379 - Loading bot...
INFO: 2022-09-21 16:05:48,664 - Запуск основного цикла...
ERROR: 2022-09-21 16:05:52,153 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON

INFO: 2022-09-21 16:05:52,154 - Reloading...
INFO: 2022-09-21 16:05:57,433 - Запуск основного цикла...
INFO: 2022-09-21 16:06:45,934 - Loading bot...
INFO: 2022-09-21 16:06:46,188 - Запуск основного цикла...
ERROR: 2022-09-21 16:06:47,878 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON

INFO: 2022-09-21 16:06:47,879 - Reloading...
INFO: 2022-09-21 16:06:53,176 - Запуск основного цикла...
INFO: 2022-09-21 16:07:42,631 - Loading bot...
INFO: 2022-09-21 16:07:42,920 - Запуск основного цикла...
ERROR: 2022-09-21 16:07:44,388 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 37, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 48, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON

INFO: 2022-09-21 16:07:44,388 - Reloading...
INFO: 2022-09-21 16:07:49,666 - Запуск основного цикла...
INFO: 2022-09-21 16:08:27,916 - Loading bot...
INFO: 2022-09-21 16:08:28,193 - Запуск основного цикла...
ERROR: 2022-09-21 16:08:29,999 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 37, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 48, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON

INFO: 2022-09-21 16:08:29,999 - Reloading...
INFO: 2022-09-21 16:08:35,322 - Запуск основного цикла...
ERROR: 2022-09-21 16:10:51,050 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 37, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 48, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON

INFO: 2022-09-21 16:10:51,051 - Reloading...
INFO: 2022-09-21 16:10:56,192 - Loading bot...
INFO: 2022-09-21 16:10:56,464 - Запуск основного цикла...
ERROR: 2022-09-21 16:10:59,278 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 37, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 48, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON, note that you should not use ' to wrap strings, use " instead

INFO: 2022-09-21 16:10:59,278 - Reloading...
INFO: 2022-09-21 16:11:04,598 - Запуск основного цикла...
INFO: 2022-09-21 16:11:40,287 - Loading bot...
INFO: 2022-09-21 16:11:40,574 - Запуск основного цикла...
ERROR: 2022-09-21 16:11:42,476 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 38, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 49, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON, note that you should not use ' to wrap strings, use " instead

INFO: 2022-09-21 16:11:42,476 - Reloading...
INFO: 2022-09-21 16:11:47,768 - Запуск основного цикла...
INFO: 2022-09-21 16:12:27,828 - Loading bot...
INFO: 2022-09-21 16:12:28,116 - Запуск основного цикла...
ERROR: 2022-09-21 16:12:30,510 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 38, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 49, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON, note that you should not use ' to wrap strings, use " instead

INFO: 2022-09-21 16:12:30,510 - Reloading...
INFO: 2022-09-21 16:12:35,813 - Запуск основного цикла...
INFO: 2022-09-21 16:15:43,644 - Loading bot...
INFO: 2022-09-21 16:15:43,922 - Запуск основного цикла...
ERROR: 2022-09-21 16:15:54,205 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 39, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 50, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: message is empty or invalid

INFO: 2022-09-21 16:15:54,206 - Reloading...
INFO: 2022-09-21 16:15:59,508 - Запуск основного цикла...
INFO: 2022-09-21 16:16:47,049 - Loading bot...
INFO: 2022-09-21 16:16:47,333 - Запуск основного цикла...
INFO: 2022-09-21 16:17:05,209 - Loading bot...
INFO: 2022-09-21 16:17:05,505 - Запуск основного цикла...
ERROR: 2022-09-21 16:17:14,663 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: message is empty or invalid

INFO: 2022-09-21 16:17:14,664 - Reloading...
INFO: 2022-09-21 16:17:19,986 - Запуск основного цикла...
INFO: 2022-09-21 16:20:55,718 - Loading bot...
INFO: 2022-09-21 16:20:56,026 - Запуск основного цикла...
ERROR: 2022-09-21 16:21:01,600 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 37, in start
    keyboard=self.get_keyboard(btn_list=buttons))
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 65, in get_keyboard
    f = json.dump(keyboard, ensure_ascii=False)
TypeError: dump() missing 1 required positional argument: 'fp'

INFO: 2022-09-21 16:21:01,600 - Reloading...
INFO: 2022-09-21 16:21:06,857 - Запуск основного цикла...
INFO: 2022-09-21 16:23:55,894 - Loading bot...
INFO: 2022-09-21 16:23:56,187 - Запуск основного цикла...
ERROR: 2022-09-21 16:24:00,246 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 37, in start
    keyboard=self.get_keyboard(btn_list=buttons))
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 65, in get_keyboard
    json.dump(keyboard, f, ensure_ascii=False)
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

INFO: 2022-09-21 16:24:00,246 - Reloading...
INFO: 2022-09-21 16:24:05,495 - Запуск основного цикла...
INFO: 2022-09-21 16:24:40,894 - Loading bot...
INFO: 2022-09-21 16:24:41,152 - Запуск основного цикла...
ERROR: 2022-09-21 16:24:44,401 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON

INFO: 2022-09-21 16:24:44,401 - Reloading...
INFO: 2022-09-21 16:24:49,699 - Запуск основного цикла...
INFO: 2022-09-21 16:36:29,565 - Loading bot...
INFO: 2022-09-21 16:36:29,881 - Запуск основного цикла...
ERROR: 2022-09-21 16:36:53,939 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: message is empty or invalid

INFO: 2022-09-21 16:36:53,940 - Reloading...
INFO: 2022-09-21 16:36:59,215 - Запуск основного цикла...
INFO: 2022-09-21 16:37:56,762 - Loading bot...
INFO: 2022-09-21 16:37:57,031 - Запуск основного цикла...
ERROR: 2022-09-21 16:37:59,705 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: message is empty or invalid

INFO: 2022-09-21 16:37:59,706 - Reloading...
INFO: 2022-09-21 16:38:05,011 - Запуск основного цикла...
INFO: 2022-09-21 16:38:11,076 - Loading bot...
INFO: 2022-09-21 16:38:11,333 - Запуск основного цикла...
ERROR: 2022-09-21 16:38:13,511 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: message is empty or invalid

INFO: 2022-09-21 16:38:13,511 - Reloading...
INFO: 2022-09-21 16:38:18,796 - Запуск основного цикла...
INFO: 2022-09-21 16:38:38,155 - Loading bot...
INFO: 2022-09-21 16:38:38,435 - Запуск основного цикла...
ERROR: 2022-09-21 16:38:42,586 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: message is empty or invalid

INFO: 2022-09-21 16:38:42,586 - Reloading...
INFO: 2022-09-21 16:38:47,879 - Запуск основного цикла...
INFO: 2022-09-21 16:39:14,420 - Loading bot...
INFO: 2022-09-21 16:39:14,705 - Запуск основного цикла...
ERROR: 2022-09-21 16:39:16,514 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: message is empty or invalid

INFO: 2022-09-21 16:39:16,515 - Reloading...
INFO: 2022-09-21 16:39:21,802 - Запуск основного цикла...
INFO: 2022-09-21 16:40:16,866 - Loading bot...
INFO: 2022-09-21 16:40:17,122 - Запуск основного цикла...
ERROR: 2022-09-21 16:40:19,598 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: message is empty or invalid

INFO: 2022-09-21 16:40:19,599 - Reloading...
INFO: 2022-09-21 16:40:24,885 - Запуск основного цикла...
INFO: 2022-09-21 16:40:50,599 - Loading bot...
INFO: 2022-09-21 16:40:50,902 - Запуск основного цикла...
ERROR: 2022-09-21 16:40:52,627 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: message is empty or invalid

INFO: 2022-09-21 16:40:52,628 - Reloading...
INFO: 2022-09-21 16:40:57,927 - Запуск основного цикла...
INFO: 2022-09-21 16:41:42,587 - Loading bot...
INFO: 2022-09-21 16:41:42,906 - Запуск основного цикла...
INFO: 2022-09-21 16:42:05,088 - Loading bot...
INFO: 2022-09-21 16:42:05,349 - Запуск основного цикла...
INFO: 2022-09-21 16:43:52,377 - Loading bot...
INFO: 2022-09-21 16:43:52,633 - Запуск основного цикла...
ERROR: 2022-09-21 16:43:55,751 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON

INFO: 2022-09-21 16:43:55,752 - Reloading...
INFO: 2022-09-21 16:44:01,046 - Запуск основного цикла...
INFO: 2022-09-21 16:44:19,102 - Loading bot...
INFO: 2022-09-21 16:44:19,375 - Запуск основного цикла...
ERROR: 2022-09-21 16:44:21,044 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON

INFO: 2022-09-21 16:44:21,044 - Reloading...
INFO: 2022-09-21 16:44:26,331 - Запуск основного цикла...
INFO: 2022-09-21 16:44:56,688 - Loading bot...
INFO: 2022-09-21 16:44:56,972 - Запуск основного цикла...
ERROR: 2022-09-21 16:44:58,680 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON

INFO: 2022-09-21 16:44:58,680 - Reloading...
INFO: 2022-09-21 16:45:03,949 - Запуск основного цикла...
INFO: 2022-09-21 16:45:33,758 - Loading bot...
INFO: 2022-09-21 16:45:34,051 - Запуск основного цикла...
ERROR: 2022-09-21 16:47:08,589 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: message is empty or invalid

INFO: 2022-09-21 16:47:08,589 - Reloading...
INFO: 2022-09-21 16:47:13,874 - Запуск основного цикла...
INFO: 2022-09-21 16:52:52,786 - Loading bot...
INFO: 2022-09-21 16:52:53,095 - Запуск основного цикла...
ERROR: 2022-09-21 16:52:57,492 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [911] Keyboard format is invalid: keyboard contains unknown fields

INFO: 2022-09-21 16:52:57,493 - Reloading...
INFO: 2022-09-21 16:53:02,778 - Запуск основного цикла...
ERROR: 2022-09-21 16:53:05,044 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 36, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 47, in send_msg
    self.vk.method('messages.send', {'peer_id': peer_id, 'message': msg, "keyboard": keyboard,'random_id': 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [911] Keyboard format is invalid: keyboard contains unknown fields

INFO: 2022-09-21 16:53:05,045 - Reloading...
INFO: 2022-09-21 16:53:10,333 - Запуск основного цикла...
INFO: 2022-09-21 17:02:08,468 - Loading bot...
INFO: 2022-09-21 17:02:08,745 - Запуск основного цикла...
INFO: 2022-09-21 17:05:12,134 - Loading bot...
INFO: 2022-09-21 17:05:12,444 - Запуск основного цикла...
INFO: 2022-09-21 17:05:54,666 - Loading bot...
INFO: 2022-09-21 17:05:54,947 - Запуск основного цикла...
INFO: 2022-09-21 17:07:52,682 - Loading bot...
INFO: 2022-09-21 17:07:52,969 - Запуск основного цикла...
INFO: 2022-09-21 17:10:39,521 - Loading bot...
INFO: 2022-09-21 17:10:39,796 - Запуск основного цикла...
INFO: 2022-09-21 17:11:31,631 - Loading bot...
INFO: 2022-09-21 17:11:31,931 - Запуск основного цикла...
INFO: 2022-09-21 17:12:44,241 - Loading bot...
INFO: 2022-09-21 17:12:44,519 - Запуск основного цикла...
ERROR: 2022-09-21 17:12:45,214 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 43, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
UnboundLocalError: local variable 'from_id' referenced before assignment

INFO: 2022-09-21 17:12:45,214 - Reloading...
INFO: 2022-09-21 17:12:50,504 - Запуск основного цикла...
INFO: 2022-09-21 17:13:11,425 - Loading bot...
INFO: 2022-09-21 17:13:11,715 - Запуск основного цикла...
ERROR: 2022-09-21 17:13:15,413 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 42, in start
    msg = event.obj['message']['text'].lower()
KeyError: 'message'

INFO: 2022-09-21 17:13:15,413 - Reloading...
INFO: 2022-09-21 17:13:21,030 - Loading bot...
INFO: 2022-09-21 17:13:21,300 - Запуск основного цикла...
ERROR: 2022-09-21 17:13:27,365 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 42, in start
    msg = event.obj['message']['text'].lower()
KeyError: 'message'

INFO: 2022-09-21 17:13:27,366 - Reloading...
INFO: 2022-09-21 17:13:32,650 - Запуск основного цикла...
INFO: 2022-09-21 17:16:42,967 - Loading bot...
INFO: 2022-09-21 17:16:43,238 - Запуск основного цикла...
ERROR: 2022-09-21 17:16:45,285 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 45, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 56, in send_msg
    self.vk.method('messages.send', {"peer_id": peer_id, "message": msg, "keyboard": keyboard, "random_id": 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [911] Keyboard format is invalid: keyboard contains unknown fields

INFO: 2022-09-21 17:16:45,285 - Reloading...
INFO: 2022-09-21 17:16:50,567 - Запуск основного цикла...
INFO: 2022-09-21 17:17:13,397 - Loading bot...
INFO: 2022-09-21 17:17:13,666 - Запуск основного цикла...
ERROR: 2022-09-21 17:17:20,538 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 46, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 57, in send_msg
    self.vk.method('messages.send', {"peer_id": peer_id, "message": msg, "keyboard": keyboard, "random_id": 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [911] Keyboard format is invalid: keyboard contains unknown fields

INFO: 2022-09-21 17:17:20,538 - Reloading...
INFO: 2022-09-21 17:17:25,819 - Запуск основного цикла...
INFO: 2022-09-21 17:20:40,365 - Loading bot...
INFO: 2022-09-21 17:20:40,650 - Запуск основного цикла...
ERROR: 2022-09-21 17:20:44,868 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 46, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 57, in send_msg
    self.vk.method('messages.send', {"peer_id": peer_id, "message": msg, "keyboard": keyboard, "random_id": 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [911] Keyboard format is invalid: keyboard contains unknown fields

INFO: 2022-09-21 17:20:44,868 - Reloading...
INFO: 2022-09-21 17:20:50,150 - Запуск основного цикла...
INFO: 2022-09-21 17:32:17,729 - Loading bot...
INFO: 2022-09-21 17:32:18,007 - Запуск основного цикла...
INFO: 2022-09-21 17:32:57,956 - Loading bot...
INFO: 2022-09-21 17:32:58,256 - Запуск основного цикла...
ERROR: 2022-09-21 17:33:03,528 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 50, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 61, in send_msg
    self.vk.method('messages.send', {"peer_id": peer_id, "message": msg, "keyboard": keyboard, "random_id": 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [911] Keyboard format is invalid: keyboard contains unknown fields

INFO: 2022-09-21 17:33:03,529 - Reloading...
INFO: 2022-09-21 17:33:08,821 - Запуск основного цикла...
INFO: 2022-09-21 17:33:40,599 - Loading bot...
INFO: 2022-09-21 17:33:40,886 - Запуск основного цикла...
INFO: 2022-09-21 17:34:22,075 - Loading bot...
INFO: 2022-09-21 17:34:22,351 - Запуск основного цикла...
INFO: 2022-09-21 17:35:03,204 - Loading bot...
INFO: 2022-09-21 17:35:03,467 - Запуск основного цикла...
INFO: 2022-09-21 17:35:59,928 - Loading bot...
INFO: 2022-09-21 17:36:00,201 - Запуск основного цикла...
ERROR: 2022-09-21 17:36:26,510 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 40, in start
    self.send_msg(peer_id=from_id, msg=self.handler.msg_handler(msg),
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 62, in send_msg
    self.vk.method('messages.send', {"peer_id": peer_id, "message": msg, "keyboard": keyboard, "random_id": 0})
  File "C:\Users\Nata\AppData\Local\Programs\Python\Python38\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [911] Keyboard format is invalid: keyboard contains unknown fields

INFO: 2022-09-21 17:36:26,510 - Reloading...
INFO: 2022-09-21 17:36:31,783 - Запуск основного цикла...
INFO: 2022-09-21 17:40:16,823 - Loading bot...
INFO: 2022-09-21 17:40:17,092 - Запуск основного цикла...
INFO: 2022-09-21 17:41:26,252 - Loading bot...
INFO: 2022-09-21 17:41:26,517 - Запуск основного цикла...
INFO: 2022-09-21 17:58:21,663 - Loading bot...
INFO: 2022-09-21 17:58:21,964 - Запуск основного цикла...
INFO: 2022-09-21 17:59:11,405 - Loading bot...
INFO: 2022-09-21 17:59:11,678 - Запуск основного цикла...
INFO: 2022-09-21 18:00:31,884 - Loading bot...
INFO: 2022-09-21 18:00:32,153 - Запуск основного цикла...
INFO: 2022-09-21 18:01:30,005 - Loading bot...
INFO: 2022-09-21 18:01:30,267 - Запуск основного цикла...
ERROR: 2022-09-21 18:01:39,243 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 854, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 327, in __getattr__
    return getattr(self.comparator, key)
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1244, in __getattr__
    return self._fallback_getattr(key)
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\orm\properties.py", line 420, in _fallback_getattr
    return getattr(self.__clause_element__(), key)
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 856, in __getattr__
    util.raise_(
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
AttributeError: Neither 'AnnotatedColumn' object nor 'Comparator' object has an attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 43, in start
    goods = db.get_goods_by_cty(msg)
  File "C:\Users\Nata\PycharmProjects\VKAPI\databases.py", line 47, in get_goods_by_cty
    category = self.session.query(Category.id).filter(Category.name.lower() == cty).all()
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 329, in __getattr__
    util.raise_(
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Category.name has an attribute 'lower'

INFO: 2022-09-21 18:01:39,243 - Reloading...
INFO: 2022-09-21 18:01:44,546 - Запуск основного цикла...
ERROR: 2022-09-21 18:01:47,025 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 854, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 327, in __getattr__
    return getattr(self.comparator, key)
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1244, in __getattr__
    return self._fallback_getattr(key)
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\orm\properties.py", line 420, in _fallback_getattr
    return getattr(self.__clause_element__(), key)
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 856, in __getattr__
    util.raise_(
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
AttributeError: Neither 'AnnotatedColumn' object nor 'Comparator' object has an attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 43, in start
    goods = db.get_goods_by_cty(msg)
  File "C:\Users\Nata\PycharmProjects\VKAPI\databases.py", line 47, in get_goods_by_cty
    category = self.session.query(Category.id).filter(Category.name.lower() == cty).all()
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 329, in __getattr__
    util.raise_(
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Category.name has an attribute 'lower'

INFO: 2022-09-21 18:01:47,025 - Reloading...
INFO: 2022-09-21 18:01:52,330 - Запуск основного цикла...
INFO: 2022-09-21 18:02:23,288 - Loading bot...
INFO: 2022-09-21 18:02:23,604 - Запуск основного цикла...
ERROR: 2022-09-21 18:02:27,719 - error: Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 854, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 327, in __getattr__
    return getattr(self.comparator, key)
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1244, in __getattr__
    return self._fallback_getattr(key)
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\orm\properties.py", line 420, in _fallback_getattr
    return getattr(self.__clause_element__(), key)
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 856, in __getattr__
    util.raise_(
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
AttributeError: Neither 'AnnotatedColumn' object nor 'Comparator' object has an attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Nata\PycharmProjects\VKAPI\vk_bot.py", line 43, in start
    goods = db.get_goods_by_cty(msg)
  File "C:\Users\Nata\PycharmProjects\VKAPI\databases.py", line 47, in get_goods_by_cty
    category = self.session.query(Category.id).filter(Category.name.lower() == cty).all()
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 329, in __getattr__
    util.raise_(
  File "C:\Users\Nata\PycharmProjects\VKAPI\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Category.name has an attribute 'lower'

INFO: 2022-09-21 18:02:27,719 - Reloading...
INFO: 2022-09-21 18:02:33,015 - Запуск основного цикла...
INFO: 2022-09-21 18:07:54,534 - Loading bot...
INFO: 2022-09-21 18:07:54,794 - Запуск основного цикла...
INFO: 2022-09-21 18:08:25,041 - Loading bot...
INFO: 2022-09-21 18:08:25,317 - Запуск основного цикла...
INFO: 2022-09-21 18:08:43,964 - Loading bot...
INFO: 2022-09-21 18:08:44,219 - Запуск основного цикла...
INFO: 2022-09-21 18:09:52,972 - Loading bot...
INFO: 2022-09-21 18:09:53,225 - Запуск основного цикла...
INFO: 2022-09-21 18:10:20,725 - Loading bot...
INFO: 2022-09-21 18:10:21,000 - Запуск основного цикла...
INFO: 2022-09-21 18:13:16,874 - Loading bot...
INFO: 2022-09-21 18:13:17,189 - Запуск основного цикла...
INFO: 2022-09-21 18:15:45,838 - Loading bot...
INFO: 2022-09-21 18:15:46,098 - Запуск основного цикла...
